version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
#   command: --check-caps false
    volumes:
      - ./output:/home/irisowner/irisdev/app/output/
    ports: 
      - 1972:1972
      - 52773:52773
      - 53773:53773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    networks:
      - app_local_network
  web:
    container_name: app_web
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - 5000:80
    restart: unless-stopped
    depends_on:
      - iris
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    networks:
      - app_local_network
networks:
  app_local_network:
    name: app_local_network
